version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0
jobs:
  docker_push: 
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      # - docker/build:
      #     image: tanyadovzhenko/auth-nestjs
      #     tag: latest
      # - docker/push:
      #     image: tanyadovzhenko/auth-nestjs
      #     auth:
      #       username: tanyadovzhenko
      #       password: tanyaddzz11
      #     tag: latest
      - run:
          name: Login Docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
workflows:
  auth-workflow:
    jobs:
      # - node_build        
      - docker_push
          # requires:
          #   - node_build
