version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0
jobs:
  docker_push: 
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login Docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker build
          command: |
            docker build -t tanyadovzhenko/auth-nestjs .
      - run:
          name: Docker push
          command: |
            docker push tanyadovzhenko/auth-nestjs
  aws_instance: 
    steps:
      - checkout
      - run:
          name: Connect to aws instance
          command: |
            ssh ubuntu@54.152.60.99
      # - run:
      #     name: Docker build
      #     command: |
      #       docker build -t tanyadovzhenko/auth-nestjs .
      # - run:
      #     name: Docker push
      #     command: |
      #       docker push tanyadovzhenko/auth-nestjs
workflows:
  auth-workflow:
    jobs:
      # - node_build        
      - docker_push
      - aws_instance
          # requires:
          #   - node_build
