version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0
jobs:
  node_build: 
    executor: node/default 
    steps:
      - checkout
      - node/install:
          node-version: "16.15.1"
      - run:
          command: npm i
          name: Run installation of packages
      - run:
          name: Run build
          command: npm run build
  docker_push: 
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: Docker login
          command: echo "$PARAM_DOCKER_PASSWORD" | docker login -u "$PARAM_DOCKER_USERNAME" --password-stdin "$PARAM_REGISTRY"
      - docker/build:
          image: tanyadovzhenko/auth-nestjs
          tag: latest
      - docker/push:
          image: tanyadovzhenko/auth-nestjs
          tag: latest
workflows:
  auth-workflow:
    jobs:
      - node_build        
      - docker_push:
          requires:
            - node_build
